"""
config.py — Central configuration for the Dizel language model.

All hyperparameters live here so you can tune them in one place.
The defaults target ~20M parameters on a single GPU with ~4 GB VRAM.
"""

from dataclasses import dataclass, field
from typing import Optional
import os


# ---------------------------------------------------------------------------
# Model Architecture
# ---------------------------------------------------------------------------
@dataclass
class ModelConfig:
    # Vocabulary size — set automatically after tokenizer training
    vocab_size: int = 16000

    # Maximum sequence (context) length in tokens
    context_length: int = 256

    # Transformer hidden dimension
    d_model: int = 256

    # Number of transformer layers
    n_layers: int = 6

    # Number of attention heads  (d_model must be divisible by n_heads)
    n_heads: int = 4

    # Feed-forward expansion factor (FFN hidden dim = d_model * ffn_mult)
    ffn_mult: int = 4

    # Dropout rate — higher helps regularise on tiny datasets
    dropout: float = 0.30

    # Tie embedding weights with LM head (saves ~3M params, aids generalisation)
    weight_tying: bool = True

    # Bias in attention projections and MLP
    bias: bool = False

    @property
    def head_dim(self) -> int:
        assert self.d_model % self.n_heads == 0, \
            f"d_model ({self.d_model}) must be divisible by n_heads ({self.n_heads})"
        return self.d_model // self.n_heads

    @property
    def ffn_dim(self) -> int:
        return self.d_model * self.ffn_mult

    def param_estimate(self) -> int:
        """Rough parameter count (ignoring biases and LayerNorm)."""
        vocab   = self.vocab_size * self.d_model          # embeddings
        pos     = self.context_length * self.d_model      # positional
        attn    = 4 * self.d_model * self.d_model         # QKV + out proj
        ffn     = 2 * self.d_model * self.ffn_dim         # two linear layers
        layer   = (attn + ffn) * self.n_layers
        lm_head = 0 if self.weight_tying else self.vocab_size * self.d_model
        return vocab + pos + layer + lm_head


# ---------------------------------------------------------------------------
# Tokenizer
# ---------------------------------------------------------------------------
@dataclass
class TokenizerConfig:
    # SentencePiece BPE model path (generated by train_tokenizer.py)
    model_path: str = "tokenizer/dizel.model"
    vocab_size: int = 16000         # must match ModelConfig.vocab_size
    character_coverage: float = 1.0
    # Special tokens
    pad_id:  int = 0
    bos_id:  int = 1
    eos_id:  int = 2
    unk_id:  int = 3


# ---------------------------------------------------------------------------
# Pre-training
# ---------------------------------------------------------------------------
@dataclass
class PretrainConfig:
    # Data
    data_path:      str   = "data/english.md"
    train_split:    float = 0.90        # fraction used for training
    seed:           int   = 42

    # Optimisation
    batch_size:     int   = 2           # micro-batch (sequences per step)
    grad_accum:     int   = 4           # effective batch = batch_size * grad_accum
    max_steps:      int   = 5000        # total optimiser steps (increased for larger corpus)
    warmup_steps:   int   = 200
    lr:             float = 3e-4        # peak learning rate
    min_lr:         float = 3e-5        # cosine decay floor
    weight_decay:   float = 0.1
    grad_clip:      float = 1.0

    # Mixed precision (set False if your GPU does not support fp16/bf16)
    use_amp:        bool  = False       # disabled for CPU-only
    amp_dtype:      str   = "bfloat16"  # "bfloat16" or "float16"

    # Logging & checkpoints
    eval_interval:  int   = 200
    eval_iters:     int   = 50          # batches averaged for val loss
    save_interval:  int   = 500
    checkpoint_dir: str   = "checkpoints"
    log_dir:        str   = "logs"
    run_name:       str   = "dizel-pretrain"

    # Overfitting mitigation on small data
    # DataLoader will shuffle and re-pack windows every epoch
    reshuffle_every_n_steps: int = 500


# ---------------------------------------------------------------------------
# Supervised Fine-Tuning (SFT / basic chat)
# ---------------------------------------------------------------------------
@dataclass
class SFTConfig:
    sft_data_path:  str   = "sft_data/chat_expanded.jsonl"
    base_checkpoint: str  = ""          # path to pretrained .pt file
    output_dir:     str   = "checkpoints"
    run_name:       str   = "dizel-sft"

    batch_size:     int   = 4
    grad_accum:     int   = 4
    max_steps:      int   = 4000
    warmup_steps:   int   = 50
    lr:             float = 1e-4
    min_lr:         float = 1e-5
    weight_decay:   float = 0.05
    grad_clip:      float = 1.0

    use_amp:        bool  = False       # disabled for CPU-only
    amp_dtype:      str   = "bfloat16"

    eval_interval:  int   = 100
    eval_iters:     int   = 20
    save_interval:  int   = 250

    # Only compute loss on the assistant turns (ignore user/system tokens)
    mask_prompt_loss: bool = True


# ---------------------------------------------------------------------------
# Data Cleaning
# ---------------------------------------------------------------------------
@dataclass
class DataCleanConfig:
    normalise_unicode:     bool  = True
    min_tokens_per_line:   int   = 3
    max_char_repeat:       int   = 5
    max_symbol_ratio:      float = 0.40
    remove_duplicates:     bool  = True


# ---------------------------------------------------------------------------
# Inference / CLI Chat
# ---------------------------------------------------------------------------
@dataclass
class InferenceConfig:
    checkpoint:     str   = ""          # path to .pt checkpoint to load
    max_new_tokens: int   = 200
    temperature:    float = 0.8
    top_k:          int   = 50
    top_p:          float = 0.92        # nucleus sampling
    repetition_penalty: float = 1.15
    device:         str   = "cpu"       # "cuda" or "cpu"


# ---------------------------------------------------------------------------
# Convenience: one object that holds everything
# ---------------------------------------------------------------------------
@dataclass
class DizelConfig:
    model:      ModelConfig      = field(default_factory=ModelConfig)
    tokenizer:  TokenizerConfig  = field(default_factory=TokenizerConfig)
    pretrain:   PretrainConfig   = field(default_factory=PretrainConfig)
    sft:        SFTConfig        = field(default_factory=SFTConfig)
    inference:  InferenceConfig  = field(default_factory=InferenceConfig)
    data_clean: DataCleanConfig  = field(default_factory=DataCleanConfig)


# Singleton used throughout the project
CONFIG = DizelConfig()


# ---------------------------------------------------------------------------
# Special tokens used in chat formatting
# ---------------------------------------------------------------------------
class SPECIAL:
    USER_START = "\u003c|user|\u003e"
    USER_END   = "\u003c|end|\u003e"
    ASST_START = "\u003c|assistant|\u003e"
    ASST_END   = "\u003c|end|\u003e"
    EOS        = "\u003c/s\u003e"
    EOS_TAG    = "\u003c|end|\u003e"


if __name__ == "__main__":
    cfg = DizelConfig()
    est = cfg.model.param_estimate()
    print(f"Dizel Model Configuration")
    print(f"  vocab_size     : {cfg.model.vocab_size:,}")
    print(f"  context_length : {cfg.model.context_length}")
    print(f"  d_model        : {cfg.model.d_model}")
    print(f"  n_layers       : {cfg.model.n_layers}")
    print(f"  n_heads        : {cfg.model.n_heads}")
    print(f"  ffn_dim        : {cfg.model.ffn_dim}")
    print(f"  dropout        : {cfg.model.dropout}")
    print(f"  weight_tying   : {cfg.model.weight_tying}")
    print(f"  ≈ parameters   : {est / 1e6:.1f} M")
