"""
config.py — Central configuration for the Dizel language model.

All hyperparameters live here so you can tune them in one place.
The defaults target ~252M parameters (Dizel v1.2) on a single GPU.
"""

from dataclasses import dataclass, field
from typing import Optional
import os


# ---------------------------------------------------------------------------
# Model Architecture
# ---------------------------------------------------------------------------
@dataclass
class ModelConfig:
    # Vocabulary size — set automatically after tokenizer training
    vocab_size: int = 32000

    # Maximum sequence (context) length in tokens
    context_length: int = 2048

    # Transformer hidden dimension
    d_model: int = 896

    # Number of transformer layers
    n_layers: int = 20

    # Number of attention heads  (d_model must be divisible by n_heads)
    n_heads: int = 16

    # Feed-forward expansion factor (FFN hidden dim = d_model * ffn_mult)
    ffn_mult: float = 3.5

    # Dropout rate — lower with larger datasets
    dropout: float = 0.05

    # Tie embedding weights with LM head (saves params, aids generalisation)
    weight_tying: bool = True

    # Bias in attention projections and MLP
    bias: bool = False

    # RoPE frequency base (v1.2+, replaces learned positional embeddings)
    rope_base: float = 10000.0

    @property
    def head_dim(self) -> int:
        assert self.d_model % self.n_heads == 0, \
            f"d_model ({self.d_model}) must be divisible by n_heads ({self.n_heads})"
        return self.d_model // self.n_heads

    @property
    def ffn_dim(self) -> int:
        return int(self.d_model * self.ffn_mult)

    def param_estimate(self) -> int:
        """Rough parameter count (ignoring biases and LayerNorm)."""
        vocab   = self.vocab_size * self.d_model          # embeddings
        # RoPE has no learnable params — pos_emb removed in v1.2
        attn    = 4 * self.d_model * self.d_model         # QKV + out proj
        ffn     = 2 * self.d_model * self.ffn_dim         # two linear layers
        layer   = (attn + ffn) * self.n_layers
        lm_head = 0 if self.weight_tying else self.vocab_size * self.d_model
        return vocab + layer + lm_head


# ---------------------------------------------------------------------------
# Tokenizer
# ---------------------------------------------------------------------------
@dataclass
class TokenizerConfig:
    # SentencePiece BPE model path (generated by train_tokenizer.py)
    model_path: str = "tokenizer/dizel.model"
    vocab_size: int = 32000         # must match ModelConfig.vocab_size
    character_coverage: float = 1.0
    # Special tokens
    pad_id:  int = 0
    bos_id:  int = 1
    eos_id:  int = 2
    unk_id:  int = 3


# ---------------------------------------------------------------------------
# Pre-training
# ---------------------------------------------------------------------------
@dataclass
class PretrainConfig:
    # Data
    data_path:      str   = "data/pretrain_v12.txt"
    train_split:    float = 0.90        # fraction used for training
    seed:           int   = 42

    # Optimisation (tuned for ~205M model on T4)
    batch_size:     int   = 2           # micro-batch (halved for VRAM)
    grad_accum:     int   = 32          # effective batch = 64 sequences
    max_steps:      int   = 15000       # reduced for v1.2.1 trimmed data
    warmup_steps:   int   = 1500        # proportional warmup
    lr:             float = 3e-5        # peak LR for 205M
    min_lr:         float = 3e-6        # cosine decay floor
    weight_decay:   float = 0.01
    grad_clip:      float = 1.0

    # Mixed precision (set False if your GPU does not support fp16/bf16)
    use_amp:        bool  = False       # disabled for CPU-only
    amp_dtype:      str   = "float16"   # T4 only supports float16, not bfloat16

    # Logging & checkpoints
    eval_interval:  int   = 500
    eval_iters:     int   = 50          # batches averaged for val loss
    save_interval:  int   = 1000
    checkpoint_dir: str   = "checkpoints"
    log_dir:        str   = "logs"
    run_name:       str   = "dizel-pretrain"

    # Overfitting mitigation on small data
    reshuffle_every_n_steps: int = 500

    # v1.2 pipeline optimizations
    shard_size_mb:  int   = 100          # tokenization shard size
    cache_dir:      str   = ".cache/tokenized"
    num_workers:    int   = 2            # DataLoader CPU workers
    resume_enabled: bool  = True         # resume from cached shards


# ---------------------------------------------------------------------------
# Supervised Fine-Tuning (SFT / basic chat)
# ---------------------------------------------------------------------------
@dataclass
class SFTConfig:
    sft_data_path:  str   = "sft_data/chat_expanded.jsonl"
    base_checkpoint: str  = ""          # path to pretrained .pt file
    output_dir:     str   = "checkpoints"
    run_name:       str   = "dizel-sft"

    batch_size:     int   = 1           # T4 VRAM constraint
    grad_accum:     int   = 32          # effective batch = 32 sequences
    max_steps:      int   = 10000       # reduced for v1.2.1 trimmed mix
    warmup_steps:   int   = 400         # proportional to reduced steps
    lr:             float = 2e-5        # learning rate for 205M
    min_lr:         float = 2e-6
    weight_decay:   float = 0.05
    grad_clip:      float = 1.0

    use_amp:        bool  = False       # disabled for CPU-only
    amp_dtype:      str   = "float16"    # T4 only supports float16

    eval_interval:  int   = 250         # more frequent eval with fewer steps
    eval_iters:     int   = 50
    save_interval:  int   = 500         # more checkpoints to pick from

    # Only compute loss on the assistant turns (ignore user/system tokens)
    mask_prompt_loss: bool = True


# ---------------------------------------------------------------------------
# Data Cleaning
# ---------------------------------------------------------------------------
@dataclass
class DataCleanConfig:
    normalise_unicode:     bool  = True
    min_tokens_per_line:   int   = 3
    max_char_repeat:       int   = 5
    max_symbol_ratio:      float = 0.40
    remove_duplicates:     bool  = True


# ---------------------------------------------------------------------------
# Inference / CLI Chat
# ---------------------------------------------------------------------------
@dataclass
class InferenceConfig:
    checkpoint:     str   = ""          # path to .pt checkpoint to load
    max_new_tokens: int   = 200
    temperature:    float = 0.8
    top_k:          int   = 50
    top_p:          float = 0.92        # nucleus sampling
    repetition_penalty: float = 1.15
    device:         str   = "cpu"       # "cuda" or "cpu"


# ---------------------------------------------------------------------------
# Convenience: one object that holds everything
# ---------------------------------------------------------------------------
@dataclass
class DizelConfig:
    model:      ModelConfig      = field(default_factory=ModelConfig)
    tokenizer:  TokenizerConfig  = field(default_factory=TokenizerConfig)
    pretrain:   PretrainConfig   = field(default_factory=PretrainConfig)
    sft:        SFTConfig        = field(default_factory=SFTConfig)
    inference:  InferenceConfig  = field(default_factory=InferenceConfig)
    data_clean: DataCleanConfig  = field(default_factory=DataCleanConfig)


# Singleton used throughout the project
CONFIG = DizelConfig()


# ---------------------------------------------------------------------------
# Mila Configuration (sister model — conversational, warm, friendly)
# ---------------------------------------------------------------------------
@dataclass
class MilaModelConfig(ModelConfig):
    """Mila architecture — same Transformer base, smaller dims."""
    vocab_size: int = 32000
    context_length: int = 1024
    d_model: int = 768
    n_layers: int = 12
    n_heads: int = 12
    ffn_mult: int = 4
    dropout: float = 0.05
    weight_tying: bool = True
    bias: bool = False
    rope_base: float = 10000.0


@dataclass
class MilaTokenizerConfig:
    """Mila uses a separate tokenizer trained on conversational data."""
    model_path: str = "tokenizer/mila.model"
    vocab_size: int = 32000
    character_coverage: float = 1.0
    pad_id: int = 0
    bos_id: int = 1
    eos_id: int = 2
    unk_id: int = 3


@dataclass
class MilaPretrainConfig:
    data_path:      str   = "data/mila_pretrain.txt"
    train_split:    float = 0.90
    seed:           int   = 42
    batch_size:     int   = 4
    grad_accum:     int   = 16
    max_steps:      int   = 20000
    warmup_steps:   int   = 1000
    lr:             float = 2e-4
    min_lr:         float = 2e-5
    weight_decay:   float = 0.01
    grad_clip:      float = 1.0
    use_amp:        bool  = False
    amp_dtype:      str   = "float16"
    eval_interval:  int   = 500
    eval_iters:     int   = 50
    save_interval:  int   = 1000
    checkpoint_dir: str   = "checkpoints"
    log_dir:        str   = "logs"
    run_name:       str   = "mila-pretrain"
    reshuffle_every_n_steps: int = 500

    # v1.2 pipeline optimizations
    shard_size_mb:  int   = 100
    cache_dir:      str   = ".cache/tokenized"
    num_workers:    int   = 2
    resume_enabled: bool  = True


@dataclass
class MilaSFTConfig:
    sft_data_path:  str   = "sft_data/mila_sft.jsonl"
    base_checkpoint: str  = ""
    output_dir:     str   = "checkpoints"
    run_name:       str   = "mila-sft"
    batch_size:     int   = 2
    grad_accum:     int   = 32
    max_steps:      int   = 5000
    warmup_steps:   int   = 400
    lr:             float = 2e-5
    min_lr:         float = 2e-6
    weight_decay:   float = 0.05
    grad_clip:      float = 1.0
    use_amp:        bool  = False
    amp_dtype:      str   = "float16"
    eval_interval:  int   = 250
    eval_iters:     int   = 50
    save_interval:  int   = 500
    mask_prompt_loss: bool = True


@dataclass
class MilaConfig:
    """Complete configuration for the Mila model."""
    model:      MilaModelConfig      = field(default_factory=MilaModelConfig)
    tokenizer:  MilaTokenizerConfig  = field(default_factory=MilaTokenizerConfig)
    pretrain:   MilaPretrainConfig   = field(default_factory=MilaPretrainConfig)
    sft:        MilaSFTConfig        = field(default_factory=MilaSFTConfig)
    inference:  InferenceConfig      = field(default_factory=InferenceConfig)
    data_clean: DataCleanConfig      = field(default_factory=DataCleanConfig)


MILA_CONFIG = MilaConfig()


# ---------------------------------------------------------------------------
# Special tokens used in chat formatting (shared by Dizel and Mila)
# ---------------------------------------------------------------------------
class SPECIAL:
    USER_START = "\u003c|user|\u003e"
    USER_END   = "\u003c|end|\u003e"
    ASST_START = "\u003c|assistant|\u003e"
    ASST_END   = "\u003c|end|\u003e"
    EOS        = "\u003c/s\u003e"
    EOS_TAG    = "\u003c|end|\u003e"


if __name__ == "__main__":
    for name, cfg in [("Dizel v1.2", DizelConfig()), ("Mila", MilaConfig())]:
        est = cfg.model.param_estimate()
        print(f"\n{name} Configuration")
        print(f"  vocab_size     : {cfg.model.vocab_size:,}")
        print(f"  context_length : {cfg.model.context_length}")
        print(f"  d_model        : {cfg.model.d_model}")
        print(f"  n_layers       : {cfg.model.n_layers}")
        print(f"  n_heads        : {cfg.model.n_heads}")
        print(f"  ffn_dim        : {cfg.model.ffn_dim}")
        print(f"  dropout        : {cfg.model.dropout}")
        print(f"  weight_tying   : {cfg.model.weight_tying}")
        print(f"  rope_base      : {cfg.model.rope_base}")
        print(f"  ~ parameters   : {est / 1e6:.1f} M")

